/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 */


pluginManagement {
    repositories {
        google()              // Required for Android plugin
        gradlePluginPortal()  // Required for Kotlin plugin (if used)
        mavenCentral()        // Optional fallback
    }
}

rootProject.name = "CardinalLibProject"
include(":CardinalLib")  // Include your Android library module
